import jsPDF from 'jspdf';

export interface KPIExportData {
  id: string;
  name: string;
  aggregatedMetric: string;
  currentValue: string;
  targetValue: string;
  frequency?: string;
  targetDate?: string;
}

export interface CampaignExportData {
  id: string;
  name: string;
  kpis: KPIExportData[];
  exportDate: Date;
}

export function exportCampaignKPIsToPDF(data: CampaignExportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  doc.setFontSize(20);
  doc.text('Campaign KPI Report', margin, yPosition);
  yPosition += 10;

  doc.setFontSize(12);
  doc.text(`Campaign: ${data.name}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Export Date: ${new Date(data.exportDate).toLocaleDateString()}`, margin, yPosition);
  yPosition += 15;

  doc.setFontSize(14);
  doc.text('Key Performance Indicators', margin, yPosition);
  yPosition += 10;

  if (data.kpis.length === 0) {
    doc.setFontSize(11);
    doc.text('No KPIs configured for this campaign.', margin, yPosition);
  } else {
    data.kpis.forEach((kpi, index) => {
      if (yPosition > 260) {
        doc.addPage();
        yPosition = margin;
      }

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${kpi.name}`, margin, yPosition);
      yPosition += 7;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      
      const currentNum = parseFloat(kpi.currentValue) || 0;
      const targetNum = parseFloat(kpi.targetValue) || 0;
      const progress = targetNum > 0 ? ((currentNum / targetNum) * 100).toFixed(1) : '0.0';

      const details = [
        `Metric: ${kpi.aggregatedMetric}`,
        `Current Value: ${currentNum.toLocaleString()}`,
        `Target Value: ${targetNum.toLocaleString()}`,
        `Progress: ${progress}%`
      ];

      if (kpi.frequency) {
        details.push(`Frequency: ${kpi.frequency}`);
      }
      if (kpi.targetDate) {
        details.push(`Target Date: ${new Date(kpi.targetDate).toLocaleDateString()}`);
      }

      details.forEach(detail => {
        doc.text(detail, margin + 5, yPosition);
        yPosition += 5;
      });

      yPosition += 5;
    });
  }

  doc.setFontSize(8);
  const footer = `Generated by PerformanceCore on ${new Date().toLocaleString()}`;
  doc.text(footer, margin, doc.internal.pageSize.getHeight() - 10);

  doc.save(`${data.name.replace(/\s+/g, '_')}_KPI_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
