import { describe, expect, it } from "vitest";
import { readFileSync } from "fs";
import { join } from "path";

describe("campaign Executive Summary regression guard", () => {
  it("guards the endpoint and builds current values from the shared aggregate contract", () => {
    const routes = readFileSync(join(process.cwd(), "server", "routes-oauth.ts"), "utf-8");
    const routeStart = routes.indexOf('app.get("/api/campaigns/:id/executive-summary"');
    const routeEnd = routes.indexOf("// ============================================================================", routeStart);
    const route = routes.slice(routeStart, routeEnd);

    expect(route).toContain("const campaign = await ensureCampaignAccess(req as any, res as any, id);");
    expect(route).not.toContain("const campaign = await storage.getCampaign(id);");
    expect(route).not.toContain("performing strongly with 1.93x ROAS");
    expect(route).not.toContain("Recommend increasing LinkedIn");
    expect(route).toContain("const performanceSummary = buildPerformanceSummaryAggregate({");
    expect(route).toContain("const metaConnection = await storage.getMetaConnection(id).catch(() => null);");
    expect(route).toContain("if (metaConnection && !(metaConnection as any).spendOnly) {");
    expect(route).toContain("dateRange: executiveDateRange");
    expect(route).toContain("const metrics = await ga4Service.getMetricsWithAutoRefresh(id, storage, ga4DateRange, primaryPropertyId || undefined, campaignFilter);");
    expect(route).toContain('periodParam === "90d" ? "90daysAgo" : "30daysAgo"');
    expect(route).toContain("let usedGA4SourceTruth = false;");
    expect(route).toContain("if (!usedGA4SourceTruth) {");
    expect(route).toContain("ga4: { connected: hasGA4Connection, ...ga4Metrics }");
    expect(route).toContain("const spendBreakdown = await storage.getSpendBreakdownBySource(id, \"1900-01-01\", endDate).catch(() => []);");
    expect(route).toContain("const revenueBreakdown = await storage.getRevenueBreakdownBySource(id, \"1900-01-01\", endDate, \"ga4\").catch(() => []);");
    expect(route).toContain("const aggregateRevenue = hasGA4Connection");
    expect(route).toContain("parseFloat((ga4Metrics.revenue + importedRevenueToDateTotal).toFixed(2))");
    expect(route).toContain("spendSource: performanceSummarySpend > 0 ? \"persisted_spend_sources\" : \"platform_spend_fallback\"");
    expect(route).toContain("meta: { connected: hasMetaConnection");
    expect(route).toContain("const aggregateMetricValue = (metricName: string): number => {");
    expect(route).toContain('const totalImpressions = aggregateMetricValue("impressions");');
    expect(route).toContain('const totalClicks = aggregateMetricValue("clicks");');
    expect(route).toContain('const totalConversions = aggregateMetricValue("conversions");');
    expect(route).toContain('const totalSpend = aggregateMetricValue("spend");');
    expect(route).toContain('const totalRevenue = aggregateMetricValue("revenue");');
    expect(route).toContain('const roas = aggregateMetricValue("roas");');
    expect(route).toContain('const roi = aggregateMetricValue("roi");');
    expect(route).toContain('const ctr = aggregateMetricValue("ctr");');
    expect(route).toContain('const cvr = aggregateMetricValue("cvr");');
    expect(route).toContain("const aggregateMetricAvailable = (metricName: string) => aggregateMetric(metricName)?.available === true;");
    expect(route).toContain("const aggregateMetricValueOrNull = (metricName: string): number | null =>");
    expect(route).toContain('roi: aggregateMetricValueOrNull("roi")');
    expect(route).toContain('roas: aggregateMetricValueOrNull("roas")');
    expect(route).toContain('ctr: aggregateMetricValueOrNull("ctr")');
    expect(route).toContain('cvr: aggregateMetricValueOrNull("cvr")');
    expect(route).toContain("const kpiMetricAliases: Record<string, string> = {");
    expect(route).toContain('totalusers: "users"');
    expect(route).toContain('totalrevenue: "revenue"');
    expect(route).toContain('totalconversions: "conversions"');
    expect(route).toContain('roas: "roas"');
    expect(route).toContain("const kpis = await storage.getCampaignKPIs(id);");
    expect(route).toContain("const aggregateKpiMetric = resolveKpiAggregateMetric(kpi);");
    expect(route).toContain("if (!aggregateKpiMetric) continue;");
    expect(route).toContain("const currentValue = aggregateMetricValue(aggregateKpiMetric);");
    expect(route).not.toContain("await storage.getKPIProgress(kpi.id)");
    expect(route).not.toContain("parseNum(kpi.currentValue)");
    expect(route).toContain("const benchmarks = await storage.getCampaignBenchmarks(id);");
    expect(route).toContain("const aggregateBenchmarkMetric = resolveKpiAggregateMetric(bm);");
    expect(route).toContain("if (!aggregateBenchmarkMetric) continue;");
    expect(route).toContain("const currentVal = aggregateMetricValue(aggregateBenchmarkMetric);");
    expect(route).toContain("const progressPct = progressRatio * 100;");
    expect(route).toContain("status: progressPct >= 90 ? 'on_track' : progressPct >= 70 ? 'needs_attention' : 'behind'");
    expect(route).not.toContain("parseNum(bm.currentValue)");
    expect(route).toContain("const snapshotPerformanceSummary = (snapshot: any) => snapshot?.metrics?.performanceSummary || null;");
    expect(route).toContain("currentSnapshotSummary.version === previousSnapshotSummary?.version");
    expect(route).not.toContain("parseNum(comparisonData.current.totalConversions) * (totalRevenue / (totalConversions || 1))");
    expect(route).toContain("const riskExtraFactors: Array<{ type: string; message: string; severity?: string }> = [];");
    expect(route).toContain("const missedKpiCount = kpiProgress.filter((kpi: any) => Number(kpi.pctComplete) < 70).length;");
    expect(route).toContain('const missedBenchmarkCount = benchmarkComparison.filter((bm: any) => bm.status === "behind").length;');
    expect(route).toContain("dataFreshnessWarnings.forEach((warning: any) => {");
    expect(route).toContain("}, growthTrajectory, trendPercentage, riskExtraFactors);");
    expect(route).toContain("checkedInputs: risk.checkedInputs");

    const summaryStart = route.indexOf("// CEO summary");
    const summaryEnd = route.indexOf("// Recommendations from helper", summaryStart);
    const summaryBlock = route.slice(summaryStart, summaryEnd);
    expect(summaryBlock).not.toContain("healthResult.grade");
    expect(summaryBlock).not.toContain("performing exceptionally");
    expect(summaryBlock).not.toContain("recommend increased investment");
    expect(summaryBlock).toContain('aggregateMetricAvailable("roi")');
    expect(summaryBlock).toContain('aggregateMetricAvailable("roas")');
    expect(summaryBlock).toContain("Risk level is ${risk.riskLevel}.");
    expect(summaryBlock).toContain("7-day snapshot trajectory does not have enough compatible history yet.");
  });

  it("derives main platform rows from performanceSummary sources and excludes financial child inputs", () => {
    const routes = readFileSync(join(process.cwd(), "server", "routes-oauth.ts"), "utf-8");
    const routeStart = routes.indexOf('app.get("/api/campaigns/:id/executive-summary"');
    const routeEnd = routes.indexOf("// ============================================================================", routeStart);
    const route = routes.slice(routeStart, routeEnd);

    expect(route).toContain("const mainAggregateSources = Array.isArray((performanceSummary as any)?.sources)");
    expect(route).toContain('source?.connected === true && source?.category !== "financial"');
    expect(route).toContain("const platformsForDisplay: any[] = mainAggregateSources.map");
    expect(route).toContain("let executiveRevenueSources: any[] = [];");
    expect(route).toContain("const revenueBreakdown = await storage.getRevenueBreakdownBySource(id, \"1900-01-01\", endDate, \"ga4\").catch(() => []);");
    expect(route).toContain("revenueSources: executiveRevenueSources");
    expect(route).toContain("name: source.label");
    expect(route).toContain("sourceId: source.id");
    expect(route).toContain("includedMetrics: source.includedMetrics");
    expect(route).toContain("excludedMetrics: source.excludedMetrics");
    expect(route).not.toContain("spend: 0,\n          revenue: 0,\n          conversions: ga4Metrics.conversions");
    expect(route).toContain("performanceSummary,");
    expect(route).toContain("aggregateVersion: (performanceSummary as any)?.version");
  });

  it("renders Executive Overview current values from aggregate availability", () => {
    const page = readFileSync(join(process.cwd(), "client", "src", "pages", "executive-summary.tsx"), "utf-8");
    const campaignDetailPage = readFileSync(join(process.cwd(), "client", "src", "pages", "campaign-detail.tsx"), "utf-8");
    const overviewStart = page.indexOf('<TabsContent value="overview"');
    const overviewEnd = page.indexOf('{/* Strategic Recommendations Tab */}', overviewStart);
    const overview = page.slice(overviewStart, overviewEnd);

    expect(page).not.toContain("const [period");
    expect(page).not.toContain('params.set("period"');
    expect(page).not.toContain("<Select value={period}");
    expect(page).toContain('const executiveOutcomeDateRange = "90days";');
    expect(page).toContain("`/api/campaigns/${campaignId}/outcome-totals?dateRange=${executiveOutcomeDateRange}${demoMode ? \"&demo=1\" : \"\"}`");
    expect(page).toContain("const performanceSummary = (outcomeTotals as any)?.performanceSummary || (executiveSummary as any).performanceSummary;");
    expect(page).toContain("const aggregateMetric = (metricName: string) => (performanceSummary as any)?.totals?.[metricName];");
    expect(page).toContain("const formatAggregateInteger = (metricName: string) =>");
    expect(page).toContain("aggregateMetricAvailable(metricName) ? Math.round(aggregateMetricValue(metricName)).toLocaleString() : \"Unavailable\";");
    expect(page).toContain('if (aggregateMetricAvailable("roi")) executiveMetricParts.push(`ROI is ${formatAggregatePercent("roi")}`);');
    expect(page).toContain('if (aggregateMetricAvailable("roas")) executiveMetricParts.push(`ROAS is ${formatAggregateRatio("roas")}`);');
    expect(page).toContain("const executiveSummaryNarrative = `${(campaign as any)?.name}: ${executiveMetricSummary} Risk level is ${displayedRiskLevel}. ${executiveTrajectorySummary}`;");
    expect(page).toContain("const resolveKpiAggregateMetric = (kpi: any): string | null => {");
    expect(page).toContain("const executiveKpiProgress = Array.isArray((executiveSummary as any).kpiProgress)");
    expect(page).toContain("? (executiveSummary as any).kpiProgress.filter((kpi: any) => resolveKpiAggregateMetric(kpi))");
    expect(page).toContain("const executiveBenchmarkComparison = Array.isArray((executiveSummary as any).benchmarkComparison)");
    expect(page).toContain("const aggregateBenchmarkMetric = resolveKpiAggregateMetric(bm);");
    expect(page).toContain("const yours = aggregateMetricValue(aggregateBenchmarkMetric);");
    expect(page).toContain("status: progressPct >= 90 ? 'on_track' : progressPct >= 70 ? 'needs_attention' : 'behind'");
    expect(page).toContain("if (!aggregateKpiMetric) return null;");
    expect(page).toContain("const current = aggregateMetricValue(aggregateKpiMetric);");
    expect(page).toContain("const kpiProgressPct = (kpi: any): number => {");
    expect(page).toContain("const riskKpiMissCount = executiveKpiProgress.filter((kpi: any) => kpiProgressPct(kpi) < 70).length;");
    expect(page).toContain('const riskBenchmarkMissCount = executiveBenchmarkComparison.filter((bm: any) => bm.status === "behind").length;');
    expect(page).toContain("const paidRiskSources = aggregateSources.filter((source: any) =>");
    expect(page).toContain("const displayedRiskFactors = [");
    expect(page).toContain('detail: aggregateMetricAvailable("roi") ? formatAggregatePercent("roi") : aggregateMetricReason("roi")');
    expect(page).toContain('detail: aggregateMetricAvailable("roas") ? formatAggregateRatio("roas") : aggregateMetricReason("roas")');
    expect(page).not.toContain("const riskCheckedInputs = Array.isArray((executiveSummary as any)?.risk?.checkedInputs)");
    expect(page).not.toContain("(executiveSummary as any).risk.factors.length === 0");
    expect(page).not.toContain("(executiveSummary as any).risk.factors.map");
    expect(page).not.toContain("(executiveSummary as any).risk.level === 'low'");
    expect(page).not.toContain("Number(kpi.current) || 0");
    expect(page).toContain("const targetDeltaPct = target > 0");
    expect(page).toContain("const progressRatio = target > 0");
    expect(page).toContain("const statusLabel = targetDeltaPct > 5 ? 'Above Target' :");
    expect(page).toContain("targetDeltaPct >= -5 ? 'On Track' : 'Below Target';");
    expect(page).toContain("const barColor = targetDeltaPct > 5 ? 'bg-green-500' :");
    expect(page).toContain("targetDeltaPct >= -5 ? 'bg-blue-500' : 'bg-red-500';");
    expect(page).toContain("{formatKpiValue(aggregateKpiMetric, current, kpi.unit)}");
    expect(page).toContain('<Progress value={pct} className="h-2" indicatorClassName={barColor} />');
    expect(page).toContain("{executiveBenchmarkComparison.map((bm: any, index: number) => (");
    expect(page).toContain("{formatKpiValue(bm.aggregateMetric, bm.yours, bm.unit)}");
    expect(page).toContain("{formatKpiValue(bm.aggregateMetric, bm.benchmark, bm.unit)}");
    expect(page).toContain("bm.status === 'on_track' ? 'bg-green-500' : bm.status === 'needs_attention' ? 'bg-yellow-500' : 'bg-red-500'");
    expect(page).toContain("bm.status === 'on_track' ? 'bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300' : bm.status === 'needs_attention' ? 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900 dark:text-yellow-300' : 'bg-red-100 text-red-700 dark:bg-red-900 dark:text-red-300'");
    expect(page).not.toContain("const pct = kpi.pctComplete || (kpi.target > 0 ? Math.min((kpi.current / kpi.target) * 100, 100) : 0);");
    expect(page).not.toContain("{kpi.status.replace('_', ' ')}");
    expect(page).not.toContain("{kpi.priority}");
    expect(page).not.toContain("2,984");
    expect(page).not.toContain("2984");
    expect(page).toContain('const reachMetricKey = pickFirstAvailableMetric(["impressions", "users", "sessions"]);');
    expect(page).toContain('const engagementMetricKey = pickFirstAvailableMetric(["clicks", "sessions", "users"]);');
    expect(page).toContain("const funnelPathLabel = `${reachMetricLabels[reachMetricKey]} -> ${engagementMetricLabels[engagementMetricKey]} -> Conversions -> Revenue`;");
    expect(overview).toContain("{funnelPathLabel}");
    expect(overview).toContain("{reachStageQuestion}");
    expect(overview).toContain("{engagementStageQuestion}");
    expect(overview).toContain("Are visits becoming conversions and revenue?");
    expect(overview).toContain("{executiveSummaryNarrative}");
    expect(overview).not.toContain("{(executiveSummary as any).ceoSummary}");
    expect(overview).not.toContain("Campaign Story:");
    expect(overview).not.toContain("Connected sources show spend");
    expect(overview).not.toContain("Platform Performance");
    expect(overview).not.toContain("Website Analytics Only");
    expect(overview).not.toContain("Excellent");
    expect(overview).not.toContain("Good");
    expect(overview).not.toContain("Fair");
    expect(overview).not.toContain("Campaign Grade");
    expect(overview).not.toContain("Health Score");
    expect(overview).not.toContain("Weighted from available ROI, ROAS, CTR, and CVR inputs.");
    expect(overview).not.toContain("health.grade");
    expect(overview).not.toContain("health.score");
    expect(overview).toContain("7-Day Snapshot Trajectory");
    expect(overview).toContain("Not enough history");
    expect(overview).toContain("Based on compatible aggregate snapshots, not the removed date selector.");
    expect(overview).toContain("No configured risk factors identified");
    expect(overview).toContain("Based on available connected-source inputs checked below.");
    expect(overview).toContain("Checked inputs");
    expect(overview).not.toContain("Campaign is operating within acceptable parameters");
    expect(overview).toContain("{formatAggregateNumber(reachMetricKey)} {reachMetricLabels[reachMetricKey]}");
    expect(overview).toContain("{formatAggregateNumber(engagementMetricKey)} {engagementMetricLabels[engagementMetricKey]}");
    expect(overview).toContain('{formatAggregatePercent("ctr")}');
    expect(overview).toContain('{formatAggregatePercent("cvr")}');
    expect(overview).toContain('{formatAggregateInteger("conversions")}');
    expect(overview).toContain('{formatAggregateCurrency("revenue")}');
    expect(overview).toContain('{formatAggregateRatio("roas")}');
    expect(overview).not.toContain('{formatAggregateNumber("conversions")}');
    expect(overview).not.toContain("{formatNumber((executiveSummary as any).metrics.totalImpressions)} Impressions");
    expect(overview).not.toContain("{formatNumber((executiveSummary as any).metrics.totalClicks)} Clicks");
    expect(overview).not.toContain("{formatCurrency((executiveSummary as any).metrics.totalRevenue)}");
    expect(campaignDetailPage.match(/queryClient\.invalidateQueries\(\{ queryKey: \["\/api\/campaigns", campaign\.id, "executive-summary"\] \}\);/g)?.length).toBe(6);
  });
});
